/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NovoPacote;

import java.util.ArrayList;
import java.util.List;

import controledefilas.Senha;

/**
 *
 * @author Diego Souza
 */
public class Interface extends javax.swing.JFrame {

    List<Senha> listaSenha;
    int numero;
    Senha p;
    Senha r;
    Senha c;

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
        numero = 0;
        listaSenha = new ArrayList<Senha>();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoSenha = new javax.swing.JTextField();
        botaoPrioritario = new javax.swing.JButton();
        botaoRapido = new javax.swing.JButton();
        botaoComum = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        botaoCaixa1 = new javax.swing.JButton();
        botaoCaixa2 = new javax.swing.JButton();
        botaoCaixa3 = new javax.swing.JButton();
        botaoCaixa4 = new javax.swing.JButton();
        campoSCliente = new javax.swing.JLabel();
        campoSCaixa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Para clientes:"));

        jLabel1.setText("Escolha o tipo de atendimento");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel2.setText("Sua senha é:");

        campoSenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSenhaActionPerformed(evt);
            }
        });

        botaoPrioritario.setText("Prioritario");
        botaoPrioritario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPrioritarioActionPerformed(evt);
            }
        });

        botaoRapido.setText("Rapido");
        botaoRapido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRapidoActionPerformed(evt);
            }
        });

        botaoComum.setText("Comum");
        botaoComum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoComumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(botaoComum, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botaoRapido, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botaoPrioritario, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(campoSenha))
                            .addComponent(jLabel2))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoRapido)
                    .addComponent(botaoPrioritario)
                    .addComponent(botaoComum))
                .addGap(55, 55, 55)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Para caixas:"));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        botaoCaixa1.setText("Caixa 1");
        botaoCaixa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCaixa1ActionPerformed(evt);
            }
        });

        botaoCaixa2.setText("Caixa 2");
        botaoCaixa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCaixa2ActionPerformed(evt);
            }
        });

        botaoCaixa3.setText("Caixa 3");
        botaoCaixa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCaixa3ActionPerformed(evt);
            }
        });

        botaoCaixa4.setText("Caixa 4");
        botaoCaixa4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCaixa4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botaoCaixa1, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(botaoCaixa3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botaoCaixa4, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(botaoCaixa2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(48, 48, 48))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCaixa1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoCaixa2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCaixa3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoCaixa4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        campoSCliente.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        campoSCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        campoSCliente.setText("  ... Aguarde ...");

        campoSCaixa.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        campoSCaixa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        campoSCaixa.setText("... Caixa ...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campoSCaixa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campoSCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(campoSCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(campoSCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCaixa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCaixa1ActionPerformed

        Senha prioritario = listaSenha.stream().filter(x -> "P".equals(x.getTipo())).findFirst().orElse(null);
        Senha rapido = listaSenha.stream().filter(x -> "R".equals(x.getTipo())).findFirst().orElse(null);
        Senha comum = listaSenha.stream().filter(x -> "C".equals(x.getTipo())).findFirst().orElse(null);

        if (prioritario != null) {
            campoSCaixa.setText("Caixa 1");
            campoSCliente.setText(prioritario.toString());
            listaSenha.remove(prioritario);
        } else if (rapido != null) {
            campoSCaixa.setText("Caixa 1");
            campoSCliente.setText(rapido.toString());
            listaSenha.remove(rapido);
        } else if (comum != null) {
            campoSCaixa.setText("Caixa 1");
            campoSCliente.setText(comum.toString());
            listaSenha.remove(comum);
        } 


    }//GEN-LAST:event_botaoCaixa1ActionPerformed

    private void botaoRapidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRapidoActionPerformed

        numero++;
        r = new Senha("R", numero);
        listaSenha.add(r);
        campoSenha.setText(String.valueOf(r.getTipo()) + "-" + r.getNumero());

    }//GEN-LAST:event_botaoRapidoActionPerformed

    private void campoSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSenhaActionPerformed

    }//GEN-LAST:event_campoSenhaActionPerformed

    private void botaoPrioritarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPrioritarioActionPerformed

        numero++;
        p = new Senha("P", numero);
        listaSenha.add(p);
        campoSenha.setText(String.valueOf(p.getTipo()) + "-" + p.getNumero());


    }//GEN-LAST:event_botaoPrioritarioActionPerformed

    private void botaoCaixa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCaixa2ActionPerformed

        Senha prioritario = listaSenha.stream().filter(x -> "P".equals(x.getTipo())).findFirst().orElse(null);
        Senha rapido = listaSenha.stream().filter(x -> "R".equals(x.getTipo())).findFirst().orElse(null);
        Senha comum = listaSenha.stream().filter(x -> "C".equals(x.getTipo())).findFirst().orElse(null);

        if (rapido != null) {
            campoSCaixa.setText("Caixa 2");
            campoSCliente.setText(rapido.toString());
            listaSenha.remove(rapido);
        } else if (prioritario != null) {
            campoSCaixa.setText("Caixa 2");
            campoSCliente.setText(prioritario.toString());
            listaSenha.remove(prioritario);
        } else if (comum != null) {
            campoSCaixa.setText("Caixa 2");
            campoSCliente.setText(comum.toString());
            listaSenha.remove(comum);
        } 

    }//GEN-LAST:event_botaoCaixa2ActionPerformed

    private void botaoCaixa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCaixa3ActionPerformed

        Senha prioritario = listaSenha.stream().filter(x -> "P".equals(x.getTipo())).findFirst().orElse(null);
        Senha rapido = listaSenha.stream().filter(x -> "R".equals(x.getTipo())).findFirst().orElse(null);
        Senha comum = listaSenha.stream().filter(x -> "C".equals(x.getTipo())).findFirst().orElse(null);

        if (rapido != null) {
            campoSCaixa.setText("Caixa 2");
            campoSCliente.setText(rapido.toString());
            listaSenha.remove(rapido);
        } else if (prioritario != null) {
            campoSCaixa.setText("Caixa 2");
            campoSCliente.setText(prioritario.toString());
            listaSenha.remove(prioritario);
        } else if (comum != null) {
            campoSCaixa.setText("Caixa 2");
            campoSCliente.setText(comum.toString());
            listaSenha.remove(comum);
        } 

    }//GEN-LAST:event_botaoCaixa3ActionPerformed

    private void botaoCaixa4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCaixa4ActionPerformed

        Senha prioritario = listaSenha.stream().filter(x -> "P".equals(x.getTipo())).findFirst().orElse(null);
        Senha rapido = listaSenha.stream().filter(x -> "R".equals(x.getTipo())).findFirst().orElse(null);
        Senha comum = listaSenha.stream().filter(x -> "C".equals(x.getTipo())).findFirst().orElse(null);

        if (comum != null) {
            campoSCaixa.setText("Caixa 2");
            campoSCliente.setText(comum.toString());
            listaSenha.remove(comum);
        } else if (rapido != null) {
            campoSCaixa.setText("Caixa 2");
            campoSCliente.setText(rapido.toString());
            listaSenha.remove(rapido);
        } else if (prioritario != null) {
            campoSCaixa.setText("Caixa 2");
            campoSCliente.setText(prioritario.toString());
            listaSenha.remove(prioritario);
        } 
        
    }//GEN-LAST:event_botaoCaixa4ActionPerformed

    private void botaoComumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoComumActionPerformed

        numero++;
        c = new Senha("C", numero);
        listaSenha.add(c);
        campoSenha.setText(String.valueOf(c.getTipo()) + "-" + c.getNumero());

    }//GEN-LAST:event_botaoComumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCaixa1;
    private javax.swing.JButton botaoCaixa2;
    private javax.swing.JButton botaoCaixa3;
    private javax.swing.JButton botaoCaixa4;
    private javax.swing.JButton botaoComum;
    private javax.swing.JButton botaoPrioritario;
    private javax.swing.JButton botaoRapido;
    private javax.swing.JLabel campoSCaixa;
    private javax.swing.JLabel campoSCliente;
    private javax.swing.JTextField campoSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
